// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_class_Image();
RcppExport SEXP _rcpp_module_boot_class_Capture();
RcppExport SEXP _rcpp_module_boot_class_VideoWriter();
RcppExport SEXP _rcpp_module_boot_methods_Arithmetic();
RcppExport SEXP _rcpp_module_boot_methods_Statistics();
RcppExport SEXP _rcpp_module_boot_methods_Comparisons();
RcppExport SEXP _rcpp_module_boot_methods_Logical();
RcppExport SEXP _rcpp_module_boot_methods_OpticalFlow();
RcppExport SEXP _rcpp_module_boot_methods_Blob();
RcppExport SEXP _rcpp_module_boot_methods_Morphology();
RcppExport SEXP _rcpp_module_boot_methods_Filters();
RcppExport SEXP _rcpp_module_boot_methods_Display();
RcppExport SEXP _rcpp_module_boot_methods_Draw();
RcppExport SEXP _rcpp_module_boot_methods_Geometry();
RcppExport SEXP _rcpp_module_boot_methods_Shape();
RcppExport SEXP _rcpp_module_boot_methods_Transform();
RcppExport SEXP _rcpp_module_boot_methods_Feature();
RcppExport SEXP _rcpp_module_boot_methods_Autothresh();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_class_Image", (DL_FUNC) &_rcpp_module_boot_class_Image, 0},
    {"_rcpp_module_boot_class_Capture", (DL_FUNC) &_rcpp_module_boot_class_Capture, 0},
    {"_rcpp_module_boot_class_VideoWriter", (DL_FUNC) &_rcpp_module_boot_class_VideoWriter, 0},
    {"_rcpp_module_boot_methods_Arithmetic", (DL_FUNC) &_rcpp_module_boot_methods_Arithmetic, 0},
    {"_rcpp_module_boot_methods_Statistics", (DL_FUNC) &_rcpp_module_boot_methods_Statistics, 0},
    {"_rcpp_module_boot_methods_Comparisons", (DL_FUNC) &_rcpp_module_boot_methods_Comparisons, 0},
    {"_rcpp_module_boot_methods_Logical", (DL_FUNC) &_rcpp_module_boot_methods_Logical, 0},
    {"_rcpp_module_boot_methods_OpticalFlow", (DL_FUNC) &_rcpp_module_boot_methods_OpticalFlow, 0},
    {"_rcpp_module_boot_methods_Blob", (DL_FUNC) &_rcpp_module_boot_methods_Blob, 0},
    {"_rcpp_module_boot_methods_Morphology", (DL_FUNC) &_rcpp_module_boot_methods_Morphology, 0},
    {"_rcpp_module_boot_methods_Filters", (DL_FUNC) &_rcpp_module_boot_methods_Filters, 0},
    {"_rcpp_module_boot_methods_Display", (DL_FUNC) &_rcpp_module_boot_methods_Display, 0},
    {"_rcpp_module_boot_methods_Draw", (DL_FUNC) &_rcpp_module_boot_methods_Draw, 0},
    {"_rcpp_module_boot_methods_Geometry", (DL_FUNC) &_rcpp_module_boot_methods_Geometry, 0},
    {"_rcpp_module_boot_methods_Shape", (DL_FUNC) &_rcpp_module_boot_methods_Shape, 0},
    {"_rcpp_module_boot_methods_Transform", (DL_FUNC) &_rcpp_module_boot_methods_Transform, 0},
    {"_rcpp_module_boot_methods_Feature", (DL_FUNC) &_rcpp_module_boot_methods_Feature, 0},
    {"_rcpp_module_boot_methods_Autothresh", (DL_FUNC) &_rcpp_module_boot_methods_Autothresh, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_Rvision(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
